//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHocSuDungThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHocSuDungThietBi()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int BaiHocSuDungThietBiId { get; set; }
        public string TenBaiHoc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public Nullable<int> ChuongTrinhHocId { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> HocKyId { get; set; }
        public Nullable<int> SoTiet { get; set; }
        public Nullable<int> TietTheoPPTC { get; set; }
        public Nullable<int> LoaiBaiHocId { get; set; }
        public Nullable<int> LopId { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
