//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBoThietBi
    {
        public int CanBoThietBiId { get; set; }
        public Nullable<int> VaiTroCanBoId { get; set; }
        public Nullable<int> GiaoVienId { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauQuanLy { get; set; }
        public Nullable<System.DateTime> ThoiGianHetHanQuanLy { get; set; }
        public Nullable<bool> CoTrinhDoNghiepVu { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
