//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaiHocSuDungThietBi
    {
        public int ChiTietId { get; set; }
        public Nullable<int> BaiHocSuDungThietBiId { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
