//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThietBi
    {
        public string ChiTietThietBiId { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<int> NamTheoDoi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<long> DonGia { get; set; }
        public string NuocSanXuat { get; set; }
        public Nullable<bool> LaThietBiTuLam { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public Nullable<System.DateTime> HanDung { get; set; }
        public Nullable<int> NguonCapId { get; set; }
        public Nullable<int> NguonKinhPhiCapTrenId { get; set; }
        public Nullable<int> MucDichSuDungId { get; set; }
        public string SoHieu { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
