//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuSuaChua
    {
        public string ChiTietPhieuSuaChuaId { get; set; }
        public string PhieuSuaChuaId { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public Nullable<int> SoLuongSuaChua { get; set; }
        public Nullable<long> DonGia { get; set; }
        public string PhieuGhiHongThietBiId { get; set; }
    }
}
