//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuGhiGiamThietBi
    {
        public string ChiTietPhieuGhiGiamThietBiId { get; set; }
        public string PhieuGhiGiamThietBiId { get; set; }
        public string PhieuGhiHongThietBiId { get; set; }
        public Nullable<int> SoLuongGiam { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public string LyDo { get; set; }
        public string PhieuGhiMatThietBiId { get; set; }
    }
}
