//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        public System.Guid DonViId { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<int> TieuChuanPhongId { get; set; }
        public Nullable<int> TieuChuanCoSoVatChatId { get; set; }
        public string TinhId { get; set; }
        public string HuyenId { get; set; }
        public string XaId { get; set; }
        public string DiaChi { get; set; }
        public string LoaiHinhTruong { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string FAX { get; set; }
        public string Website { get; set; }
        public Nullable<int> KhoiTruongId { get; set; }
        public string HieuTruong { get; set; }
        public string CanBoQuanLyThietBi { get; set; }
    
        public virtual KhoiTruong KhoiTruong { get; set; }
        public virtual TieuChuanPhong TieuChuanPhong { get; set; }
        public virtual TieuChuanCoSoVatChat TieuChuanCoSoVatChat { get; set; }
    }
}
