//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTrongPhieuGhiTang
    {
        public string FileTrongPhieuGhiTangId { get; set; }
        public string TenFile { get; set; }
        public string Ext { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public string PhieuGhiTangThietBiId { get; set; }
    }
}
