//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int GiaoVienId { get; set; }
        public string TenGiaoVien { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> NgayVaoNganh { get; set; }
        public Nullable<bool> DangLamViec { get; set; }
        public Nullable<int> GioiTinhId { get; set; }
        public Nullable<int> ToBoMonId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string MaGiaoVien { get; set; }
        public Nullable<System.DateTime> NgayNghiViec { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
