//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoiLopTieuChuan
    {
        public int KhoiLopTieuChuanId { get; set; }
        public string TenKhoiLop { get; set; }
        public string MaKhoiLop { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> KhoiTruongId { get; set; }
    
        public virtual KhoiTruong KhoiTruong { get; set; }
    }
}
