//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKetKhoiLopThietBi
    {
        public int LienKetId { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> KhoiLopId { get; set; }
    }
}
