//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKetNguoiDungChucVu
    {
        public int LienKetId { get; set; }
        public Nullable<int> ChucVuId { get; set; }
        public Nullable<System.Guid> NguoiDungId { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
