//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKetTietHocPhieuMuon
    {
        public int LienKetId { get; set; }
        public string MaPhieuMuon { get; set; }
        public Nullable<int> TietHocId { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual TietHoc TietHoc { get; set; }
    }
}
