//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThayDoi
    {
        public int LoaiThayDoiId { get; set; }
        public string TenLoaiThayDoi { get; set; }
        public string MaLoaiThayDoi { get; set; }
    }
}
