//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPhieuMuon
    {
        public int LogId { get; set; }
        public string MaPhieuMuon { get; set; }
        public string NguoiDung { get; set; }
        public string HanhDong { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TieuDe { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
