//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogThietBi
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaLoaiThayDoi { get; set; }
        public string SoPhieuId { get; set; }
        public Nullable<System.Guid> NguoiDungId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
    }
}
