//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHocTieuChuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHocTieuChuan()
        {
            this.ThietBiTieuChuans = new HashSet<ThietBiTieuChuan>();
        }
    
        public int MonHocTieuChuanId { get; set; }
        public string TenMonHoc { get; set; }
        public string MaMonHoc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string KhoiLopTieuChuanId { get; set; }
        public Nullable<int> KhoiTruongId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThietBiTieuChuan> ThietBiTieuChuans { get; set; }
    }
}
