//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDeNghiMuaSam
    {
        public string PhieuDeNghiMuaSamId { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NoiDung { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<bool> DaXuLy { get; set; }
        public Nullable<bool> ChotPhieu { get; set; }
        public string NguoiCapNhat { get; set; }
    }
}
