//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGhiTangThietBi
    {
        public string PhieuGhiTangThietBiId { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string ChungTuLienQuan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
    }
}
