//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGhiHongThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuGhiHongThietBi()
        {
            this.ChiTietPhieuGhiHongThietBis = new HashSet<ChiTietPhieuGhiHongThietBi>();
        }
    
        public string PhieuGhiHongThietBiId { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NoiDung { get; set; }
        public string SoPhieu { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<int> TrangThaiHongMatId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuGhiHongThietBi> ChiTietPhieuGhiHongThietBis { get; set; }
        public virtual TrangThaiHongMat TrangThaiHongMat { get; set; }
    }
}
