//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuon()
        {
            this.LienKetThietBiPhieuMuons = new HashSet<LienKetThietBiPhieuMuon>();
            this.LienKetTietHocPhieuMuons = new HashSet<LienKetTietHocPhieuMuon>();
            this.LogPhieuMuons = new HashSet<LogPhieuMuon>();
        }
    
        public string MaPhieuMuon { get; set; }
        public Nullable<int> ChuongTrinhHocId { get; set; }
        public Nullable<int> KhoiLopId { get; set; }
        public Nullable<int> GiaoVienId { get; set; }
        public Nullable<int> MucDichSuDungId { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public Nullable<int> LopHocId { get; set; }
        public Nullable<int> SoTietHoc { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.Guid> NguoiTao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BaiHocId { get; set; }
        public Nullable<int> TrangThaiPhieuMuonId { get; set; }
        public Nullable<int> LoaiPhieuMuonId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public Nullable<bool> NguoiMuonNhan { get; set; }
        public Nullable<bool> NguoiMuonTra { get; set; }
        public Nullable<bool> NguoiChoMuonGiao { get; set; }
        public Nullable<bool> NguoiChoMuonNhan { get; set; }
    
        public virtual BaiHocSuDungThietBi BaiHocSuDungThietBi { get; set; }
        public virtual ChuongTrinhHoc ChuongTrinhHoc { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual KhoiLop KhoiLop { get; set; }
        public virtual KhoPhong KhoPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienKetThietBiPhieuMuon> LienKetThietBiPhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienKetTietHocPhieuMuon> LienKetTietHocPhieuMuons { get; set; }
        public virtual LoaiPhieuMuon LoaiPhieuMuon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPhieuMuon> LogPhieuMuons { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual MucDichSuDung MucDichSuDung { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThaiPhieuMuon TrangThaiPhieuMuon { get; set; }
    }
}
