//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinhSoTietSuDungThietBi
    {
        public int QuyDinhSoTietSuDungThietBiId { get; set; }
        public Nullable<int> LopId { get; set; }
        public Nullable<int> ChuongTrinhHocId { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public Nullable<int> TietTNHKI { get; set; }
        public Nullable<int> TietTNHKII { get; set; }
        public Nullable<int> TietTHHKI { get; set; }
        public Nullable<int> TietTHHKII { get; set; }
        public Nullable<int> NamHocBatDau { get; set; }
        public Nullable<int> NamHocKetThuc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> QuyDinhSuDungSoTietId { get; set; }
    }
}
