//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungPhong
    {
        public int SuDungPhongId { get; set; }
        public Nullable<int> LopId { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public Nullable<int> NgayTrongTuan { get; set; }
        public string TietHoc { get; set; }
        public Nullable<int> ThoiKhoaBieuPhongId { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual KhoPhong KhoPhong { get; set; }
    }
}
