//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiTieuChuan
    {
        public int ThietBiId { get; set; }
        public Nullable<int> LoaiThietBiTieuChuanId { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<int> SoLuongToiThieu { get; set; }
        public Nullable<System.Guid> DonViId { get; set; }
        public Nullable<int> DonViTinhId { get; set; }
        public string MaThietBi { get; set; }
        public Nullable<int> MonHocTieuChuanId { get; set; }
        public string Mota { get; set; }
        public string KhoiLopTieuChuanId { get; set; }
        public Nullable<int> KhoiTruongId { get; set; }
        public Nullable<int> TieuChuanCoSoVatChatId { get; set; }
    
        public virtual KhoiTruong KhoiTruong { get; set; }
        public virtual LoaiThietBiTieuChuan LoaiThietBiTieuChuan { get; set; }
        public virtual MonHocTieuChuan MonHocTieuChuan { get; set; }
        public virtual TieuChuanCoSoVatChat TieuChuanCoSoVatChat { get; set; }
    }
}
