//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.ChiTietPhieuGhiHongThietBis = new HashSet<ChiTietPhieuGhiHongThietBi>();
            this.ChiTietPhieuGhiMatThietBis = new HashSet<ChiTietPhieuGhiMatThietBi>();
            this.KhoThietBis = new HashSet<KhoThietBi>();
            this.LienKetThietBiPhieuMuons = new HashSet<LienKetThietBiPhieuMuon>();
        }
    
        public int ThietBiId { get; set; }
        public string MaThietBi { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> LoaiThietBiId { get; set; }
        public Nullable<int> DonViTinhId { get; set; }
        public Nullable<bool> QuanLyTieuHao { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MonHocId { get; set; }
        public Nullable<int> SoLuongToiThieu { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.Guid> DonViId { get; set; }
        public string KhoiLopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuGhiHongThietBi> ChiTietPhieuGhiHongThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuGhiMatThietBi> ChiTietPhieuGhiMatThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoThietBi> KhoThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienKetThietBiPhieuMuon> LienKetThietBiPhieuMuons { get; set; }
        public virtual LoaiThietBi LoaiThietBi { get; set; }
    }
}
