//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieuPhong
    {
        public int Id { get; set; }
        public string TietHocSuDung { get; set; }
        public Nullable<int> KhoPhongId { get; set; }
        public Nullable<int> LopHocId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> NgayTrongTuan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
    
        public virtual KhoPhong KhoPhong { get; set; }
    }
}
