//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TietHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TietHoc()
        {
            this.LienKetTietHocPhieuMuons = new HashSet<LienKetTietHocPhieuMuon>();
        }
    
        public int TietHocId { get; set; }
        public Nullable<int> TenTietHoc { get; set; }
        public Nullable<int> BuoiTrongNgay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienKetTietHocPhieuMuon> LienKetTietHocPhieuMuons { get; set; }
    }
}
