//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChuanPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TieuChuanPhong()
        {
            this.DonVis = new HashSet<DonVi>();
            this.KhoiPhongTieuChuans = new HashSet<KhoiPhongTieuChuan>();
        }
    
        public int TieuChuanId { get; set; }
        public string TenTieuChuan { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhatCuoi { get; set; }
        public Nullable<int> KhoiLopId { get; set; }
        public Nullable<int> KhoiTruongId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVi> DonVis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoiPhongTieuChuan> KhoiPhongTieuChuans { get; set; }
    }
}
