//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBoMon
    {
        public int ToBoMonId { get; set; }
        public string MaBoMon { get; set; }
        public string TenToBoMon { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> PhongBanId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
