//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiHongMat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrangThaiHongMat()
        {
            this.PhieuGhiHongThietBis = new HashSet<PhieuGhiHongThietBi>();
            this.PhieuGhiMatThietBis = new HashSet<PhieuGhiMatThietBi>();
        }
    
        public int TrangThaiHongMatId { get; set; }
        public string TenTrangThaiHongMat { get; set; }
        public string MaMau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGhiHongThietBi> PhieuGhiHongThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuGhiMatThietBi> PhieuGhiMatThietBis { get; set; }
    }
}
